package com.epm.camaraterreno

object TraduccionesIA {

    private val mapa = mapOf(

        // ── PECES ──────────────────────────────────────────────────────────────
        "tench" to "tenca",
        "goldfish" to "pez dorado",
        "great white shark" to "tiburón blanco",
        "tiger shark" to "tiburón tigre",
        "hammerhead shark" to "tiburón martillo",
        "electric ray" to "raya eléctrica",
        "stingray" to "raya",
        "eel" to "anguila",
        "silver salmon" to "salmón plateado",
        "rock beauty" to "pez belleza de roca",
        "clownfish" to "pez payaso",
        "anemonefish" to "pez payaso",
        "sturgeon" to "esturión",
        "gar" to "pez aguja",
        "lionfish" to "pez león",
        "pufferfish" to "pez globo",
        "puffer" to "pez globo",

        // ── AVES ───────────────────────────────────────────────────────────────
        "rooster" to "gallo",
        "hen" to "gallina",
        "ostrich" to "avestruz",
        "brambling" to "pinzón montano",
        "goldfinch" to "jilguero",
        "house finch" to "pinzón doméstico",
        "junco" to "junco",
        "indigo bunting" to "azulillo",
        "american robin" to "petirrojo americano",
        "robin" to "petirrojo",
        "bulbul" to "bulbul",
        "jay" to "arrendajo",
        "magpie" to "urraca",
        "chickadee" to "carbonero",
        "water ouzel" to "mirlo acuático",
        "dipper" to "mirlo acuático",
        "kite" to "milano",
        "bald eagle" to "águila calva",
        "vulture" to "buitre",
        "great grey owl" to "búho lapón",
        "grey owl" to "búho gris",
        "owl" to "búho",
        "black grouse" to "gallo lira",
        "ptarmigan" to "perdiz nival",
        "ruffed grouse" to "urogallo",
        "prairie grouse" to "urogallo de las praderas",
        "peacock" to "pavo real",
        "quail" to "codorniz",
        "partridge" to "perdiz",
        "grey parrot" to "loro gris",
        "macaw" to "guacamayo",
        "sulphur-crested cockatoo" to "cacatúa",
        "cockatoo" to "cacatúa",
        "lorikeet" to "lorito",
        "parrot" to "loro",
        "coucal" to "cucal",
        "bee eater" to "abejaruco",
        "hornbill" to "cálao",
        "hummingbird" to "colibrí",
        "jacamar" to "jacamar",
        "toucan" to "tucán",
        "duck" to "pato",
        "red-breasted merganser" to "serreta mediana",
        "goose" to "ganso",
        "black swan" to "cisne negro",
        "swan" to "cisne",
        "white stork" to "cigüeña blanca",
        "black stork" to "cigüeña negra",
        "spoonbill" to "espátula rosada",
        "flamingo" to "flamenco",
        "little blue heron" to "garza azul",
        "great egret" to "garza real",
        "egret" to "garza",
        "heron" to "garza",
        "bittern" to "avetoro",
        "crane" to "grulla",
        "limpkin" to "carrao",
        "common gallinule" to "gallineta",
        "gallinule" to "gallineta",
        "american coot" to "focha americana",
        "coot" to "focha",
        "bustard" to "avutarda",
        "ruddy turnstone" to "vuelvepiedras",
        "dunlin" to "correlimos",
        "common redshank" to "archibebe",
        "dowitcher" to "agujeta",
        "oystercatcher" to "ostrero",
        "pelican" to "pelícano",
        "king penguin" to "pingüino rey",
        "penguin" to "pingüino",
        "albatross" to "albatros",
        "sparrow" to "gorrión",
        "pigeon" to "paloma",
        "dove" to "paloma",
        "parrot" to "loro",
        "hawk" to "halcón",
        "falcon" to "halcón",
        "eagle" to "águila",
        "condor" to "cóndor",
        "turkey" to "pavo",
        "woodpecker" to "pájaro carpintero",
        "crow" to "cuervo",
        "raven" to "cuervo",
        "swallow" to "golondrina",
        "kingfisher" to "martín pescador",
        "nightjar" to "chotacabras",

        // ── MAMÍFEROS MARINOS ──────────────────────────────────────────────────
        "grey whale" to "ballena gris",
        "whale" to "ballena",
        "killer whale" to "orca",
        "orca" to "orca",
        "dugong" to "dugongo",
        "sea lion" to "león marino",
        "seal" to "foca",
        "walrus" to "morsa",
        "dolphin" to "delfín",
        "porpoise" to "marsopa",

        // ── ANFIBIOS ───────────────────────────────────────────────────────────
        "fire salamander" to "salamandra de fuego",
        "salamander" to "salamandra",
        "smooth newt" to "tritón liso",
        "newt" to "tritón",
        "spotted salamander" to "salamandra manchada",
        "axolotl" to "ajolote",
        "american bullfrog" to "rana toro",
        "bullfrog" to "rana toro",
        "tree frog" to "rana arborícola",
        "tailed frog" to "rana de cola",
        "frog" to "rana",
        "toad" to "sapo",

        // ── REPTILES ───────────────────────────────────────────────────────────
        "loggerhead sea turtle" to "tortuga boba",
        "leatherback sea turtle" to "tortuga laúd",
        "mud turtle" to "tortuga de lodo",
        "terrapin" to "tortuga acuática",
        "box turtle" to "tortuga de caja",
        "turtle" to "tortuga",
        "tortoise" to "tortuga terrestre",
        "banded gecko" to "gecko bandeado",
        "gecko" to "gecko",
        "green iguana" to "iguana verde",
        "iguana" to "iguana",
        "carolina anole" to "anolis verde",
        "anole" to "anolis",
        "desert grassland whiptail lizard" to "lagartija látigo",
        "agama" to "agama",
        "frilled-neck lizard" to "lagarto de cuello con fuelle",
        "alligator lizard" to "lagarto aligátor",
        "gila monster" to "monstruo de Gila",
        "green lizard" to "lagarto verde",
        "lizard" to "lagarto",
        "african chameleon" to "camaleón africano",
        "chameleon" to "camaleón",
        "komodo dragon" to "dragón de Komodo",
        "nile crocodile" to "cocodrilo del Nilo",
        "crocodile" to "cocodrilo",
        "american alligator" to "aligátor americano",
        "alligator" to "aligátor",
        "triceratops" to "triceratops",
        "worm snake" to "serpiente gusano",
        "ring-necked snake" to "serpiente de collar",
        "eastern hog-nosed snake" to "serpiente hocico de cerdo",
        "smooth green snake" to "serpiente verde",
        "kingsnake" to "serpiente rey",
        "garter snake" to "serpiente de liga",
        "water snake" to "serpiente acuática",
        "vine snake" to "serpiente bejuco",
        "night snake" to "serpiente nocturna",
        "boa constrictor" to "boa constrictora",
        "boa" to "boa",
        "african rock python" to "pitón africana",
        "python" to "pitón",
        "indian cobra" to "cobra india",
        "cobra" to "cobra",
        "green mamba" to "mamba verde",
        "mamba" to "mamba",
        "sea snake" to "serpiente marina",
        "saharan horned viper" to "víbora cornuda",
        "viper" to "víbora",
        "eastern diamondback rattlesnake" to "cascabel de diamantes",
        "rattlesnake" to "serpiente cascabel",
        "sidewinder" to "serpiente de cuernos",
        "snake" to "serpiente",

        // ── ARÁCNIDOS E INSECTOS ────────────────────────────────────────────────
        "harvestman" to "segador",
        "scorpion" to "escorpión",
        "yellow garden spider" to "araña de jardín",
        "barn spider" to "araña de granero",
        "european garden spider" to "araña de jardín europea",
        "southern black widow" to "viuda negra",
        "black widow" to "viuda negra",
        "tarantula" to "tarántula",
        "wolf spider" to "araña lobo",
        "spider" to "araña",
        "tick" to "garrapata",
        "centipede" to "ciempiés",
        "tiger beetle" to "escarabajo tigre",
        "ladybug" to "mariquita",
        "ladybird" to "mariquita",
        "ground beetle" to "escarabajo de tierra",
        "longhorn beetle" to "escarabajo longicornio",
        "leaf beetle" to "crisomélido",
        "dung beetle" to "escarabajo pelotero",
        "rhinoceros beetle" to "escarabajo rinoceronte",
        "weevil" to "gorgojo",
        "beetle" to "escarabajo",
        "fly" to "mosca",
        "bee" to "abeja",
        "wasp" to "avispa",
        "ant" to "hormiga",
        "grasshopper" to "saltamontes",
        "cricket" to "grillo",
        "stick insect" to "insecto palo",
        "walking stick" to "insecto palo",
        "cockroach" to "cucaracha",
        "praying mantis" to "mantis religiosa",
        "mantis" to "mantis",
        "cicada" to "cigarra",
        "leafhopper" to "chicharrita",
        "lacewing" to "crisopa",
        "dragonfly" to "libélula",
        "damselfly" to "caballito del diablo",
        "admiral" to "mariposa almirante",
        "ringlet" to "mariposa sátiro",
        "monarch butterfly" to "mariposa monarca",
        "monarch" to "mariposa monarca",
        "small white" to "mariposa blanca",
        "sulphur butterfly" to "mariposa azufre",
        "butterfly" to "mariposa",
        "moth" to "polilla",
        "caterpillar" to "oruga",

        // ── CRUSTÁCEOS Y MOLUSCOS ──────────────────────────────────────────────
        "starfish" to "estrella de mar",
        "sea urchin" to "erizo de mar",
        "sea cucumber" to "pepino de mar",
        "conch" to "caracola",
        "snail" to "caracol",
        "slug" to "babosa",
        "sea slug" to "babosa de mar",
        "chiton" to "quitón",
        "chambered nautilus" to "nautilus",
        "nautilus" to "nautilus",
        "dungeness crab" to "cangrejo de Dungeness",
        "rock crab" to "cangrejo de roca",
        "fiddler crab" to "cangrejo violinista",
        "red king crab" to "cangrejo real rojo",
        "crab" to "cangrejo",
        "american lobster" to "langosta americana",
        "spiny lobster" to "langosta espinosa",
        "lobster" to "langosta",
        "crayfish" to "cangrejo de río",
        "hermit crab" to "cangrejo ermitaño",
        "isopod" to "isópodo",
        "shrimp" to "camarón",
        "jellyfish" to "medusa",
        "sea anemone" to "anémona de mar",
        "anemone" to "anémona",
        "brain coral" to "coral cerebro",
        "coral" to "coral",
        "coral reef" to "arrecife de coral",
        "flatworm" to "gusano plano",
        "worm" to "gusano",
        "nematode" to "nematodo",

        // ── PERROS (RAZAS) ─────────────────────────────────────────────────────
        "chihuahua" to "chihuahua",
        "japanese chin" to "chin japonés",
        "maltese" to "maltés",
        "pekingese" to "pequinés",
        "shih tzu" to "shih tzu",
        "king charles spaniel" to "spaniel rey Carlos",
        "papillon" to "papillón",
        "toy terrier" to "terrier miniatura",
        "rhodesian ridgeback" to "ridgeback de Rhodesia",
        "afghan hound" to "galgo afgano",
        "basset hound" to "basset hound",
        "basset" to "basset",
        "beagle" to "beagle",
        "bloodhound" to "sabueso",
        "greyhound" to "galgo",
        "ibizan hound" to "podenco ibicenco",
        "norwegian elkhound" to "elkhound noruego",
        "otterhound" to "otterhound",
        "saluki" to "saluki",
        "scottish deerhound" to "lebrel escocés",
        "weimaraner" to "weimaraner",
        "staffordshire bull terrier" to "bull terrier de Staffordshire",
        "american staffordshire terrier" to "terrier americano",
        "bedlington terrier" to "terrier de Bedlington",
        "border terrier" to "border terrier",
        "kerry blue terrier" to "terrier azul de Kerry",
        "irish terrier" to "terrier irlandés",
        "norfolk terrier" to "terrier de Norfolk",
        "norwich terrier" to "terrier de Norwich",
        "yorkshire terrier" to "yorkshire terrier",
        "wire fox terrier" to "fox terrier de pelo duro",
        "lakeland terrier" to "terrier lakeland",
        "sealyham terrier" to "terrier de Sealyham",
        "airedale terrier" to "airedale terrier",
        "airedale" to "airedale",
        "cairn terrier" to "terrier cairn",
        "australian terrier" to "terrier australiano",
        "dandie dinmont terrier" to "terrier Dandie Dinmont",
        "boston terrier" to "terrier de Boston",
        "miniature schnauzer" to "schnauzer miniatura",
        "giant schnauzer" to "schnauzer gigante",
        "standard schnauzer" to "schnauzer",
        "schnauzer" to "schnauzer",
        "scottish terrier" to "terrier escocés",
        "tibetan terrier" to "terrier tibetano",
        "australian silky terrier" to "terrier sedoso australiano",
        "soft-coated wheaten terrier" to "terrier de pelo suave",
        "west highland white terrier" to "westie",
        "lhasa apso" to "lhasa apso",
        "flat-coated retriever" to "retriever de pelo liso",
        "curly-coated retriever" to "retriever de pelo rizado",
        "golden retriever" to "golden retriever",
        "labrador retriever" to "labrador",
        "chesapeake bay retriever" to "retriever de Chesapeake",
        "german shorthaired pointer" to "pointer alemán",
        "vizsla" to "vizsla",
        "english setter" to "setter inglés",
        "irish setter" to "setter irlandés",
        "gordon setter" to "setter Gordon",
        "brittany spaniel" to "spaniel bretón",
        "clumber spaniel" to "spaniel clumber",
        "english springer spaniel" to "spaniel springer inglés",
        "welsh springer spaniel" to "spaniel springer galés",
        "cocker spaniel" to "cocker spaniel",
        "sussex spaniel" to "spaniel de Sussex",
        "irish water spaniel" to "spaniel de agua irlandés",
        "kuvasz" to "kuvasz",
        "schipperke" to "schipperke",
        "groenendael" to "groenendael",
        "malinois" to "malinois",
        "briard" to "briard",
        "australian kelpie" to "kelpie australiano",
        "komondor" to "komondor",
        "old english sheepdog" to "pastor inglés antiguo",
        "shetland sheepdog" to "pastor de Shetland",
        "collie" to "collie",
        "border collie" to "border collie",
        "bouvier des flandres" to "boyero de Flandes",
        "rottweiler" to "rottweiler",
        "german shepherd dog" to "pastor alemán",
        "german shepherd" to "pastor alemán",
        "dobermann" to "doberman",
        "doberman" to "doberman",
        "miniature pinscher" to "pinscher miniatura",
        "greater swiss mountain dog" to "boyero suizo",
        "bernese mountain dog" to "boyero de Berna",
        "appenzeller sennenhund" to "perro de Appenzell",
        "entlebucher mountain dog" to "boyero de Entlebuch",
        "boxer" to "bóxer",
        "bullmastiff" to "bullmastiff",
        "tibetan mastiff" to "mastín tibetano",
        "mastiff" to "mastín",
        "french bulldog" to "bulldog francés",
        "great dane" to "gran danés",
        "st. bernard" to "san bernardo",
        "saint bernard" to "san bernardo",
        "husky" to "husky",
        "alaskan malamute" to "malamute de Alaska",
        "siberian husky" to "husky siberiano",
        "dalmatian" to "dálmata",
        "affenpinscher" to "affenpinscher",
        "basenji" to "basenji",
        "pug" to "carlino",
        "leonberger" to "leonberger",
        "newfoundland" to "terranova",
        "pyrenean mountain dog" to "perro pirenaico",
        "great pyrenees" to "perro pirenaico",
        "samoyed" to "samoyedo",
        "pomeranian" to "pomerania",
        "chow chow" to "chow chow",
        "keeshond" to "keeshond",
        "griffon bruxellois" to "grifón de Bruselas",
        "pembroke welsh corgi" to "corgi de Pembroke",
        "cardigan welsh corgi" to "corgi de Cardigan",
        "corgi" to "corgi",
        "toy poodle" to "caniche miniatura",
        "miniature poodle" to "caniche miniatura",
        "standard poodle" to "caniche estándar",
        "poodle" to "caniche",
        "mexican hairless dog" to "xoloitzcuintle",
        "dingo" to "dingo",
        "dog" to "perro",

        // ── LOBOS Y ZORROS ──────────────────────────────────────────────────────
        "grey wolf" to "lobo gris",
        "alaskan tundra wolf" to "lobo de la tundra",
        "red wolf" to "lobo rojo",
        "wolf" to "lobo",
        "coyote" to "coyote",
        "african wild dog" to "licaón",
        "hyena" to "hiena",
        "red fox" to "zorro rojo",
        "kit fox" to "zorro del desierto",
        "arctic fox" to "zorro ártico",
        "grey fox" to "zorro gris",
        "fox" to "zorro",

        // ── GATOS ──────────────────────────────────────────────────────────────
        "tabby" to "gato atigrado",
        "tabby cat" to "gato atigrado",
        "tabby, tabby cat" to "gato atigrado",
        "tiger cat" to "gato tigre",
        "persian cat" to "gato persa",
        "siamese cat" to "gato siamés",
        "egyptian mau" to "mau egipcio",
        "cat" to "gato",
        "cougar" to "puma",
        "puma" to "puma",
        "lynx" to "lince",
        "leopard" to "leopardo",
        "snow leopard" to "leopardo de las nieves",
        "jaguar" to "jaguar",
        "lion" to "león",
        "tiger" to "tigre",
        "cheetah" to "guepardo",

        // ── OSOS ───────────────────────────────────────────────────────────────
        "brown bear" to "oso pardo",
        "american black bear" to "oso negro americano",
        "polar bear" to "oso polar",
        "sloth bear" to "oso perezoso",
        "bear" to "oso",
        "panda" to "panda",
        "giant panda" to "panda gigante",
        "red panda" to "panda rojo",

        // ── OTROS MAMÍFEROS ────────────────────────────────────────────────────
        "mongoose" to "mangosta",
        "meerkat" to "suricata",
        "weasel" to "comadreja",
        "mink" to "visón",
        "european polecat" to "turón europeo",
        "polecat" to "turón",
        "black-footed ferret" to "hurón de patas negras",
        "ferret" to "hurón",
        "otter" to "nutria",
        "skunk" to "mofeta",
        "badger" to "tejón",
        "armadillo" to "armadillo",
        "three-toed sloth" to "perezoso de tres dedos",
        "sloth" to "perezoso",
        "orangutan" to "orangután",
        "gorilla" to "gorila",
        "chimpanzee" to "chimpancé",
        "gibbon" to "gibón",
        "siamang" to "siamang",
        "guenon" to "guenón",
        "patas monkey" to "mono patas",
        "baboon" to "babuino",
        "macaque" to "macaco",
        "langur" to "langur",
        "black-and-white colobus" to "colobo",
        "colobus" to "colobo",
        "proboscis monkey" to "mono narigudo",
        "marmoset" to "tití",
        "white-headed capuchin" to "capuchino",
        "capuchin" to "capuchino",
        "howler monkey" to "mono aullador",
        "squirrel monkey" to "mono ardilla",
        "ring-tailed lemur" to "lémur de cola anillada",
        "lemur" to "lémur",
        "indri" to "indri",
        "monkey" to "mono",
        "asian elephant" to "elefante asiático",
        "african bush elephant" to "elefante africano",
        "elephant" to "elefante",
        "horse" to "caballo",
        "zebra" to "cebra",
        "pig" to "cerdo",
        "wild boar" to "jabalí",
        "warthog" to "facóquero",
        "hippopotamus" to "hipopótamo",
        "ox" to "buey",
        "water buffalo" to "búfalo de agua",
        "bison" to "bisonte",
        "ram" to "carnero",
        "bighorn sheep" to "carnero cimarrón",
        "alpine ibex" to "íbice alpino",
        "ibex" to "íbice",
        "sheep" to "oveja",
        "goat" to "cabra",
        "deer" to "ciervo",
        "moose" to "alce",
        "elk" to "alce",
        "hartebeest" to "alcelafino",
        "impala" to "impala",
        "gazelle" to "gacela",
        "arabian camel" to "camello árabe",
        "camel" to "camello",
        "llama" to "llama",
        "alpaca" to "alpaca",
        "giraffe" to "jirafa",
        "rhinoceros" to "rinoceronte",
        "hippopotamus" to "hipopótamo",
        "hog" to "cerdo",
        "cow" to "vaca",
        "bull" to "toro",
        "cottontail rabbit" to "conejo de cola de algodón",
        "hare" to "liebre",
        "rabbit" to "conejo",
        "angora rabbit" to "conejo de Angora",
        "hamster" to "hámster",
        "porcupine" to "puercoespín",
        "fox squirrel" to "ardilla zorra",
        "squirrel" to "ardilla",
        "marmot" to "marmota",
        "beaver" to "castor",
        "guinea pig" to "cobaya",
        "rat" to "rata",
        "mouse" to "ratón",
        "echidna" to "equidna",
        "platypus" to "ornitorrinco",
        "wallaby" to "ualabí",
        "kangaroo" to "canguro",
        "koala" to "koala",
        "wombat" to "vombátido",
        "common sorrel horse" to "caballo alazán",
        "tusker" to "elefante colmilludo",

        // ── PERROS VARIOS ──────────────────────────────────────────────────────
        "hound" to "sabueso",
        "terrier" to "terrier",
        "spaniel" to "spaniel",
        "retriever" to "retriever",
        "setter" to "setter",
        "pointer" to "pointer",

        // ── INFRAESTRUCTURA Y URBAN ────────────────────────────────────────────
        "manhole cover" to "tapa de alcantarilla",
        "water tower" to "torre de agua",
        "dam" to "presa",
        "breakwater" to "rompeolas",
        "suspension bridge" to "puente colgante",
        "through arch bridge" to "puente arco",
        "viaduct" to "viaducto",
        "traffic light" to "semáforo",
        "traffic or street sign" to "señal de tráfico",
        "street sign" to "señal de tráfico",
        "road sign" to "señal de tráfico",
        "pole" to "poste",
        "flagpole" to "asta de bandera",
        "lighthouse" to "faro",
        "fountain" to "fuente",
        "coil" to "bobina",
        "chain" to "cadena",
        "chainlink fence" to "cerca metálica",
        "split-rail fence" to "cerca de madera",
        "stone wall" to "pared de piedra",
        "hook" to "gancho",
        "padlock" to "candado",
        "combination lock" to "cerradura de combinación",
        "gas pump" to "surtidor de gasolina",
        "solar thermal collector" to "colector solar",
        "drilling rig" to "plataforma de perforación",
        "dock" to "muelle",
        "parking meter" to "parquímetro",
        "pay-phone" to "teléfono público",
        "pay phone" to "teléfono público",
        "cash machine" to "cajero automático",
        "atm" to "cajero automático",
        "mailbox" to "buzón de correo",
        "mail bag" to "bolsa de correo",
        "turnstile" to "torniquete",
        "odometer" to "medidor",
        "switch" to "interruptor",
        "radiator" to "radiador",
        "electric fan" to "ventilador eléctrico",
        "ceiling fan" to "ventilador de techo",

        // ── EDIFICIOS Y ESTRUCTURAS ────────────────────────────────────────────
        "castle" to "castillo",
        "palace" to "palacio",
        "church" to "iglesia",
        "monastery" to "monasterio",
        "mosque" to "mezquita",
        "barn" to "granero",
        "greenhouse" to "invernadero",
        "boathouse" to "embarcadero",
        "bell tower" to "campanario",
        "dome" to "cúpula",
        "library" to "biblioteca",
        "bakery" to "panadería",
        "barbershop" to "barbería",
        "grocery store" to "supermercado",
        "restaurant" to "restaurante",
        "prison" to "prisión",
        "movie theater" to "cine",
        "cinema" to "cine",
        "cliff dwelling" to "vivienda en acantilado",
        "sliding door" to "puerta corredera",
        "thatched roof" to "techo de paja",
        "tile roof" to "tejado de teja",
        "stupa" to "estupa",
        "obelisk" to "obelisco",
        "megalith" to "megalito",
        "triumphal arch" to "arco de triunfo",
        "totem pole" to "tótem",
        "stage" to "escenario",
        "patio" to "patio",
        "maze" to "laberinto",
        "altar" to "altar",
        "shoe store" to "zapatería",
        "tobacco shop" to "tabaquería",
        "toy store" to "juguetería",
        "bookstore" to "librería",
        "candy store" to "confitería",
        "confectionery" to "confitería",
        "shopping mall" to "centro comercial",

        // ── VEHÍCULOS TERRESTRES ───────────────────────────────────────────────
        "ambulance" to "ambulancia",
        "taxicab" to "taxi",
        "cab" to "taxi",
        "fire engine" to "camión de bomberos",
        "garbage truck" to "camión de basura",
        "tow truck" to "grúa remolcadora",
        "school bus" to "autobús escolar",
        "bus" to "autobús",
        "minibus" to "microbús",
        "trolleybus" to "trolebús",
        "minivan" to "minivan",
        "jeep" to "jeep",
        "motorcycle" to "motocicleta",
        "moped" to "moped",
        "motor scooter" to "scooter",
        "scooter" to "scooter",
        "tractor" to "tractor",
        "forklift" to "montacargas",
        "crane" to "grúa",
        "semi-trailer truck" to "camión semirremolque",
        "truck" to "camión",
        "police van" to "furgón policial",
        "snowplow" to "quitanieves",
        "race car" to "coche de carreras",
        "sports car" to "auto deportivo",
        "convertible" to "descapotable",
        "station wagon" to "ranchera",
        "recreational vehicle" to "vehículo recreativo",
        "mobile home" to "casa móvil",
        "limousine" to "limusina",
        "car" to "coche",
        "automobile" to "automóvil",
        "bicycle" to "bicicleta",
        "tandem bicycle" to "bicicleta tándem",
        "tricycle" to "triciclo",
        "go-kart" to "kart",
        "skateboard" to "patineta",
        "horse-drawn vehicle" to "carruaje",
        "bullock cart" to "carro de bueyes",
        "dog sled" to "trineo de perros",
        "snowmobile" to "moto de nieve",
        "half-track" to "semioruga",
        "tank" to "tanque",
        "electric locomotive" to "locomotora eléctrica",
        "steam locomotive" to "locomotora de vapor",
        "freight car" to "vagón de carga",
        "passenger car" to "vagón de pasajeros",
        "tram" to "tranvía",

        // ── VEHÍCULOS ACUÁTICOS ────────────────────────────────────────────────
        "canoe" to "canoa",
        "gondola" to "góndola",
        "catamaran" to "catamarán",
        "trimaran" to "trimarán",
        "sailboat" to "velero",
        "schooner" to "goleta",
        "motorboat" to "lancha motora",
        "lifeboat" to "bote salvavidas",
        "fireboat" to "barco de bomberos",
        "container ship" to "buque portacontenedores",
        "ocean liner" to "trasatlántico",
        "submarine" to "submarino",
        "boat" to "bote",
        "ship" to "barco",
        "paddlewheel" to "rueda de paletas",

        // ── VEHÍCULOS AÉREOS ───────────────────────────────────────────────────
        "aircraft carrier" to "portaaviones",
        "airliner" to "avión de línea",
        "airplane" to "avión",
        "airship" to "dirigible",
        "parachute" to "paracaídas",
        "space shuttle" to "transbordador espacial",
        "military aircraft" to "avión militar",
        "warplane" to "avión de guerra",
        "helicopter" to "helicóptero",

        // ── HERRAMIENTAS Y EQUIPO ──────────────────────────────────────────────
        "hammer" to "martillo",
        "shovel" to "pala",
        "chainsaw" to "motosierra",
        "power drill" to "taladro eléctrico",
        "hatchet" to "hacha pequeña",
        "nail" to "clavo",
        "bucket" to "cubo",
        "wheelbarrow" to "carretilla",
        "toolbox" to "caja de herramientas",
        "wrench" to "llave inglesa",
        "plunger" to "desatascador",
        "broom" to "escoba",
        "mop" to "trapeador",
        "paintbrush" to "pincel",
        "syringe" to "jeringa",
        "stethoscope" to "estetoscopio",
        "microscope" to "microscopio",
        "barometer" to "barómetro",
        "weighing scale" to "báscula",
        "scale" to "báscula",
        "magnetic compass" to "brújula",
        "stopwatch" to "cronómetro",
        "sundial" to "reloj de sol",
        "oscilloscope" to "osciloscopio",
        "hourglass" to "reloj de arena",
        "tripod" to "trípode",
        "binoculars" to "binoculares",
        "projector" to "proyector",
        "loupe" to "lupa",
        "slide rule" to "regla de cálculo",
        "abacus" to "ábaco",
        "combine harvester" to "cosechadora",
        "threshing machine" to "trilladora",
        "sawmill" to "aserradero",
        "potter's wheel" to "torno de alfarero",
        "sewing machine" to "máquina de coser",
        "printing press" to "imprenta",

        // ── NATURALEZA ──────────────────────────────────────────────────────────
        "valley" to "valle",
        "volcano" to "volcán",
        "alp" to "montaña nevada",
        "cliff" to "acantilado",
        "beach" to "playa",
        "sandbar" to "banco de arena",
        "geyser" to "géiser",
        "lakeshore" to "orilla del lago",
        "promontory" to "promontorio",
        "bubble" to "burbuja",
        "hay" to "heno",
        "corn" to "maíz",
        "rapeseed" to "colza",
        "acorn" to "bellota",
        "daisy" to "margarita",
        "sunflower" to "girasol",
        "rose hip" to "escaramujo",
        "horse chestnut seed" to "castaña de Indias",
        "yellow lady's slipper" to "zapatilla de dama amarilla",
        "mushroom" to "hongo",
        "agaric" to "hongo agárico",
        "bolete mushroom" to "boleto",
        "coral fungus" to "hongo coral",
        "stinkhorn mushroom" to "hongo falo",
        "earth star fungus" to "hongo estrella",
        "hen of the woods mushroom" to "maitake",
        "gyromitra" to "falsa colmenilla",
        "ear" to "mazorca",
        "web" to "telaraña",
        "honeycomb" to "panal",
        "beehive" to "colmena",
        "apiary" to "colmena",

        // ── ELECTRODOMÉSTICOS ──────────────────────────────────────────────────
        "refrigerator" to "refrigerador",
        "fridge" to "refrigerador",
        "microwave oven" to "microondas",
        "microwave" to "microondas",
        "stove" to "estufa",
        "oven" to "horno",
        "dishwasher" to "lavavajillas",
        "washing machine" to "lavadora",
        "vacuum cleaner" to "aspiradora",
        "toaster" to "tostadora",
        "clothes iron" to "plancha de ropa",
        "iron" to "plancha",
        "hair dryer" to "secador de cabello",
        "space heater" to "calefactor",
        "waffle iron" to "gofrera",
        "espresso machine" to "máquina de espresso",
        "coffeepot" to "cafetera",
        "dutch oven" to "cazuela de hierro",
        "crock pot" to "olla de cocción lenta",
        "rotisserie" to "asador rotativo",

        // ── ELECTRÓNICA ────────────────────────────────────────────────────────
        "television" to "televisión",
        "tv" to "televisión",
        "monitor" to "monitor",
        "laptop computer" to "computadora portátil",
        "notebook computer" to "computadora portátil",
        "laptop" to "computadora portátil",
        "desktop computer" to "computadora de escritorio",
        "computer keyboard" to "teclado de computadora",
        "keyboard" to "teclado",
        "printer" to "impresora",
        "photocopier" to "fotocopiadora",
        "hard disk drive" to "disco duro",
        "modem" to "módem",
        "radio" to "radio",
        "radio telescope" to "radiotelescopio",
        "remote control" to "control remoto",
        "mobile phone" to "teléfono móvil",
        "cell phone" to "teléfono móvil",
        "telephone" to "teléfono",
        "rotary dial telephone" to "teléfono de disco",
        "ipod" to "iPod",
        "cassette player" to "reproductor de casete",
        "cassette" to "casete",
        "cd player" to "reproductor de CD",
        "tape player" to "reproductor de cinta",
        "music speaker" to "altavoz",
        "loudspeaker" to "altavoz",
        "hand-held computer" to "PDA",
        "joystick" to "palanca de mando",
        "modem" to "módem",
        "speedometer" to "velocímetro",
        "odometer" to "odómetro",
        "polaroid camera" to "cámara Polaroid",
        "reflex camera" to "cámara réflex",
        "camera" to "cámara",

        // ── MUEBLES Y HOGAR ────────────────────────────────────────────────────
        "chair" to "silla",
        "folding chair" to "silla plegable",
        "rocking chair" to "mecedora",
        "barber chair" to "silla de barbero",
        "park bench" to "banco de parque",
        "bench" to "banco",
        "table lamp" to "lámpara de mesa",
        "lampshade" to "pantalla de lámpara",
        "desk" to "escritorio",
        "dining table" to "mesa de comedor",
        "table" to "mesa",
        "couch" to "sofá",
        "sofa" to "sofá",
        "chest of drawers" to "cómoda",
        "chiffonier" to "chiffonnier",
        "wardrobe" to "armario",
        "bookcase" to "estantería",
        "china cabinet" to "vitrina",
        "entertainment center" to "centro de entretenimiento",
        "four-poster bed" to "cama con dosel",
        "bassinet" to "moisés",
        "infant bed" to "cuna de bebé",
        "crib" to "cuna",
        "filing cabinet" to "archivador",
        "safe" to "caja fuerte",
        "medicine cabinet" to "botiquín",
        "fire screen" to "pantalla de chimenea",
        "doormat" to "felpudo",
        "window shade" to "persiana",
        "window screen" to "mosquitero de ventana",
        "shower curtain" to "cortina de ducha",
        "bath towel" to "toalla de baño",
        "soap dispenser" to "dispensador de jabón",
        "toilet seat" to "asiento de inodoro",
        "quilt" to "edredón",
        "pillow" to "almohada",
        "hamper" to "cesto de ropa",
        "mirror" to "espejo",
        "car mirror" to "espejo retrovisor",
        "picture frame" to "marco de foto",

        // ── RECIPIENTES Y COCINA ────────────────────────────────────────────────
        "water bottle" to "botella de agua",
        "water jug" to "jarra de agua",
        "whiskey jug" to "jarra de whisky",
        "beer bottle" to "botella de cerveza",
        "wine bottle" to "botella de vino",
        "soda bottle" to "botella de refresco",
        "milk can" to "bidón de leche",
        "barrel" to "barril",
        "rain barrel" to "barril de lluvia",
        "crate" to "cajón",
        "carton" to "cartón",
        "packet" to "paquete",
        "can opener" to "abrelatas",
        "bottle cap" to "tapa de botella",
        "pot" to "olla",
        "frying pan" to "sartén",
        "wok" to "wok",
        "kettle" to "hervidor",
        "teapot" to "tetera",
        "mixing bowl" to "tazón",
        "measuring cup" to "taza medidora",
        "ladle" to "cucharón",
        "spatula" to "espátula",
        "strainer" to "colador",
        "colander" to "colador",
        "salt shaker" to "salero",
        "cup" to "taza",
        "coffee mug" to "taza de café",
        "plate" to "plato",
        "soup bowl" to "cuenco de sopa",
        "goblet" to "cáliz",
        "beer glass" to "vaso de cerveza",
        "cocktail shaker" to "coctelera",
        "wooden spoon" to "cuchara de madera",
        "mortar and pestle" to "mortero",
        "cauldron" to "caldero",
        "beaker" to "vaso de precipitados",
        "petri dish" to "placa de Petri",
        "tray" to "bandeja",
        "pitcher" to "jarra",

        // ── ARTÍCULOS PERSONALES ───────────────────────────────────────────────
        "backpack" to "mochila",
        "umbrella" to "paraguas",
        "wallet" to "billetera",
        "purse" to "bolso",
        "handbag" to "bolso de mano",
        "suitcase" to "maleta",
        "vase" to "jarrón",
        "candle" to "vela",
        "trash can" to "papelera",
        "basket" to "cesta",
        "shopping cart" to "carrito de compras",
        "shopping basket" to "cesta de la compra",
        "envelope" to "sobre",
        "pencil case" to "estuche",
        "pencil sharpener" to "sacapuntas",
        "ruler" to "regla",
        "eraser" to "goma de borrar",
        "ballpoint pen" to "bolígrafo",
        "fountain pen" to "pluma estilográfica",
        "quill" to "pluma de escribir",
        "letter opener" to "abrecartas",
        "paper towel" to "papel de cocina",
        "toilet paper" to "papel higiénico",
        "paddle" to "remo",
        "oar" to "remo",

        // ── ROPA Y CALZADO ─────────────────────────────────────────────────────
        "suit" to "traje",
        "lab coat" to "bata de laboratorio",
        "military uniform" to "uniforme militar",
        "jersey" to "jersey",
        "sweatshirt" to "sudadera",
        "t-shirt" to "camiseta",
        "jeans" to "jeans",
        "kimono" to "kimono",
        "poncho" to "poncho",
        "apron" to "delantal",
        "bra" to "sujetador",
        "bikini" to "bikini",
        "swimming cap" to "gorro de natación",
        "tank suit" to "traje de baño",
        "tights" to "medias",
        "miniskirt" to "minifalda",
        "hoop skirt" to "miriñaque",
        "overskirt" to "sobrefalda",
        "gown" to "vestido de gala",
        "trench coat" to "gabardina",
        "fur coat" to "abrigo de piel",
        "cardigan" to "cárdigan",
        "cloak" to "capa",
        "abaya" to "abaya",
        "academic gown" to "toga",
        "sarong" to "pareo",
        "balaclava" to "pasamontañas",
        "sleeping bag" to "saco de dormir",
        "running shoe" to "zapatilla de deporte",
        "sandal" to "sandalia",
        "cowboy boot" to "bota vaquera",
        "boot" to "bota",
        "clogs" to "zuecos",
        "slip-on shoe" to "mocasín",
        "sock" to "calcetín",
        "bow tie" to "pajarita",
        "windsor tie" to "corbata",
        "bolo tie" to "bolo",
        "necklace" to "collar",
        "sunglasses" to "gafas de sol",
        "hair clip" to "pinza para el cabello",
        "wig" to "peluca",
        "hair spray" to "laca para el cabello",
        "face powder" to "polvos faciales",
        "lipstick" to "lápiz labial",
        "perfume" to "perfume",
        "lotion" to "loción",
        "sombrero" to "sombrero",
        "cowboy hat" to "sombrero vaquero",
        "military cap" to "gorra militar",
        "graduation cap" to "birrete de graduación",
        "poke bonnet" to "bonete",
        "crash helmet" to "casco de seguridad",
        "gas mask" to "máscara de gas",
        "oxygen mask" to "máscara de oxígeno",
        "mask" to "máscara",
        "bulletproof vest" to "chaleco antibalas",
        "breastplate" to "peto",
        "cuirass" to "coraza",
        "knee pad" to "rodillera",
        "glove" to "guante",
        "mitten" to "manopla",
        "scarf" to "bufanda",

        // ── DEPORTES Y OCIO ────────────────────────────────────────────────────
        "basketball" to "baloncesto",
        "football helmet" to "casco de fútbol americano",
        "tennis ball" to "pelota de tenis",
        "golf ball" to "pelota de golf",
        "golf cart" to "carrito de golf",
        "soccer ball" to "balón de fútbol",
        "volleyball" to "voleibol",
        "rugby ball" to "balón de rugby",
        "baseball" to "béisbol",
        "racket" to "raqueta",
        "skateboard" to "patineta",
        "ski" to "esquí",
        "snowboard" to "tabla de snowboard",
        "jigsaw puzzle" to "rompecabezas",
        "billiard table" to "mesa de billar",
        "pool table" to "mesa de billar",
        "slot machine" to "máquina tragamonedas",
        "hockey puck" to "disco de hockey",
        "punching bag" to "saco de boxeo",
        "dumbbell" to "mancuerna",
        "barbell" to "barra de pesas",
        "balance beam" to "barra de equilibrio",
        "parallel bars" to "barras paralelas",
        "gymnastic horizontal bar" to "barra horizontal",
        "croquet ball" to "pelota de croquet",
        "bobsled" to "bobsled",
        "snorkel" to "tubo de buceo",
        "swing" to "columpio",
        "carousel" to "carrusel",
        "kite" to "cometa",
        "balloon" to "globo",
        "teddy bear" to "osito de peluche",
        "toy" to "juguete",
        "scoreboard" to "marcador",

        // ── INSTRUMENTOS MUSICALES ─────────────────────────────────────────────
        "acoustic guitar" to "guitarra acústica",
        "electric guitar" to "guitarra eléctrica",
        "banjo" to "banjo",
        "sitar" to "sitar",
        "violin" to "violín",
        "cello" to "violonchelo",
        "harp" to "arpa",
        "grand piano" to "piano de cola",
        "upright piano" to "piano vertical",
        "piano" to "piano",
        "drum" to "tambor",
        "drum kit" to "batería",
        "drumstick" to "palillo de tambor",
        "steel drum" to "tambor de acero",
        "saxophone" to "saxofón",
        "flute" to "flauta",
        "panpipes" to "flauta de Pan",
        "oboe" to "oboe",
        "bassoon" to "fagot",
        "ocarina" to "ocarina",
        "trumpet" to "trompeta",
        "cornet" to "corneta",
        "trombone" to "trombón",
        "french horn" to "trompa francesa",
        "accordion" to "acordeón",
        "harmonica" to "armónica",
        "chime" to "carrillón",
        "bell" to "campana",
        "marimba" to "marimba",
        "maraca" to "maraca",
        "gong" to "gong",
        "bagpipe" to "gaita",

        // ── ARMAS ──────────────────────────────────────────────────────────────
        "revolver" to "revólver",
        "rifle" to "rifle",
        "assault rifle" to "fusil de asalto",
        "holster" to "pistolera",
        "cannon" to "cañón",
        "shield" to "escudo",
        "scabbard" to "vaina",
        "missile" to "misil",

        // ── COMIDA Y BEBIDA ────────────────────────────────────────────────────
        "pizza" to "pizza",
        "cheeseburger" to "hamburguesa con queso",
        "hamburger" to "hamburguesa",
        "hot dog" to "perro caliente",
        "mashed potato" to "puré de papas",
        "banana" to "banana",
        "granny smith" to "manzana Granny Smith",
        "apple" to "manzana",
        "orange" to "naranja",
        "lemon" to "limón",
        "strawberry" to "fresa",
        "pineapple" to "piña",
        "pomegranate" to "granada",
        "fig" to "higo",
        "jackfruit" to "jaca",
        "cherimoya" to "chirimoya",
        "broccoli" to "brócoli",
        "cauliflower" to "coliflor",
        "cabbage" to "repollo",
        "zucchini" to "calabacín",
        "spaghetti squash" to "calabaza espagueti",
        "acorn squash" to "calabaza bellota",
        "butternut squash" to "calabaza butternut",
        "cucumber" to "pepino",
        "bell pepper" to "pimiento",
        "artichoke" to "alcachofa",
        "cardoon" to "cardo",
        "bagel" to "bagel",
        "pretzel" to "pretzel",
        "french loaf" to "baguette",
        "baguette" to "baguette",
        "bread" to "pan",
        "dough" to "masa",
        "meat loaf" to "pastel de carne",
        "pot pie" to "pastel de olla",
        "burrito" to "burrito",
        "trifle" to "postre trifle",
        "ice cream" to "helado",
        "ice lolly" to "paleta helada",
        "consomme" to "consomé",
        "hot pot" to "olla caliente",
        "carbonara" to "carbonara",
        "chocolate sauce" to "salsa de chocolate",
        "guacamole" to "guacamole",
        "espresso" to "espresso",
        "red wine" to "vino tinto",
        "beer" to "cerveza",
        "eggnog" to "ponche de huevo",

        // ── MEDIOS Y COMUNICACIÓN ──────────────────────────────────────────────
        "comic book" to "cómic",
        "newspaper" to "periódico",
        "menu" to "menú",
        "crossword" to "crucigrama",
        "dust jacket" to "sobrecubierta",
        "book" to "libro",
        "website" to "sitio web",
        "envelope" to "sobre",

        // ── RELOJES ────────────────────────────────────────────────────────────
        "analog clock" to "reloj analógico",
        "digital clock" to "reloj digital",
        "wall clock" to "reloj de pared",
        "digital watch" to "reloj digital de pulsera",
        "watch" to "reloj de pulsera",
        "clock" to "reloj",

        // ── OBJETOS VARIOS ─────────────────────────────────────────────────────
        "lighter" to "encendedor",
        "matchstick" to "cerilla",
        "match" to "cerilla",
        "torch" to "antorcha",
        "flashlight" to "linterna",
        "candle" to "vela",
        "band-aid" to "vendaje",
        "bandage" to "vendaje",
        "stretcher" to "camilla",
        "crutch" to "muleta",
        "neck brace" to "collarín",
        "wheelchair" to "silla de ruedas",
        "car wheel" to "rueda de coche",
        "wheel" to "rueda",
        "buckle" to "hebilla",
        "safety pin" to "imperdible",
        "reel" to "carrete",
        "spindle" to "huso",
        "thimble" to "dedal",
        "wool" to "lana",
        "knot" to "nudo",
        "chain mail" to "cota de malla",
        "lock" to "cerradura",
        "key" to "llave",
        "door" to "puerta",
        "window" to "ventana",
        "gate" to "puerta de reja",
        "lamp" to "lámpara",
        "lantern" to "linterna",
        "spotlight" to "foco",
        "spice rack" to "especiero",
        "toilet paper" to "papel higiénico",
        "paper towel" to "papel de cocina",
        "book" to "libro",
        "notebook" to "cuaderno",
        "binder" to "carpeta",
        "ring binder" to "archivador de anillas",
        "tape measure" to "cinta métrica",
        "plectrum" to "plectro",
        "nipple" to "tetina",
        "pacifier" to "chupete",
        "diaper" to "pañal",
        "baby bib" to "babero",
        "stocking" to "media",
        "christmas stocking" to "bota de Navidad",
        "feather boa" to "boa de plumas",
        "fur" to "piel",
        "prayer rug" to "alfombra de oración",
        "rug" to "alfombra",
        "shoji screen" to "biombo shoji",
        "mosquito net" to "mosquitero",
        "cargo net" to "red de carga",
        "net" to "red",
        "rope" to "cuerda",
        "string" to "cuerda",
        "bow" to "arco",
        "hunting bow" to "arco de caza",
        "crossbow" to "ballesta",
        "sling" to "honda",
        "boomerang" to "bumerán",
        "whistle" to "silbato",
        "horn" to "cuerno",
        "maypole" to "palo de mayo",
        "throne" to "trono",
        "pedestal" to "pedestal",
        "bust" to "busto",
        "statue" to "estatua",
        "model t" to "Ford T",
        "yurt" to "yurta",
        "igloo" to "iglú",
        "tepee" to "tipi",
        "shipwreck" to "naufragio",
        "lifebuoy" to "salvavidas",
        "anchor" to "ancla",

        // ── SALUD Y MEDICINA ───────────────────────────────────────────────────
        "pill bottle" to "frasco de pastillas",
        "pill" to "pastilla",
        "capsule" to "cápsula",
        "thermometer" to "termómetro",
        "scalpel" to "bisturí",
        "bandage" to "vendaje",
        "cast" to "yeso",
        "brace" to "férula",

        // ── DEPORTES ADICIONALES ───────────────────────────────────────────────
        "tennis racket" to "raqueta de tenis",
        "badminton racket" to "raqueta de bádminton",
        "cricket bat" to "bate de críquet",
        "baseball bat" to "bate de béisbol",
        "golf club" to "palo de golf",
        "ski pole" to "bastón de esquí",
        "bicycle pump" to "bomba de bicicleta",
        "fishing rod" to "caña de pescar"
    )

    fun traducir(etiquetaIngles: String): String =
        mapa[etiquetaIngles.lowercase().trim()] ?: etiquetaIngles
}
